### ISSUE TITLE
请教EasyARM-RT1052调试出错问题

### ISSUE THREAD

**Issue by kzjdswjx** [zlgopen/awtk-aworks-rt1052#3]
一、开发环境
1、eclipse为eclipse_neon_2016q3_x86，SDK软件包为aworks_m105x_sdk_1.0.3-alpha；
2、参考手册：【入门指南】EasyARM RT1052 SDK 快速入门文档 eclipse V1.0.0及【用户手册】EasyARM RT1052 SDK 用户参考手册 V1.0.0；
3、完全按手册操作。
二、调试时遇到的问题如下：
1、初次在SDRAM中下载并调试easy_arm_rt1052_debug时，正常，led灯每隔500ms闪烁。
2、将500ms改为2000ms或其它，编译正常，下载调试时会报错：No source available for "0x201414"，但led灯可以按2000ms闪烁；
3、按用户手册第4章测试examples中的led示例，下载调试时会出错，程序无法正常运行。且无法会使用串口0进行调试（串口连接正常）。错误提示：
_wfi_start() at imx105x_cpu_idle.S:29 0x80003288,具体如下：
can't find a source file at
"D\MultiRunner\builds\9e1b3274\0\aworks2\aw_imxrt105x/source\cpu\imx1050\source/imx105x_cpu_idle.s"

**Comment by kzjdswjx** [comment]
刚开始学习awtk平台，请问管理员是什么原因导致的，或者哪位也遇到过这个问题？指导一下，谢谢。

**Comment by sosotan** [comment]
问题2  下载调试报错没有关系，只要能正常下断点调试就行了

问题3  aworks_m105x_sdk_1.0.3-alpha 这个版本比较老，并且无法跑AWTK
建议在我们官网上下载最新的 1.0.4 或者等 1.0.5 更新

**Comment by sosotan** [comment]
可以用这个工程更简单   https://github.com/zlgopen/awtk-easyarm-rt1052-raw
